apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-monappc-monappc-frontend-cert
  namespace: dev-monappc-monappc-frontend
spec:
  secretName: dev-monappc-monappc-frontend-tls
  dnsNames:
    - dev.monappc.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
