apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-monappc-monappc-frontend-cert
  namespace: staging-monappc-monappc-frontend
spec:
  secretName: staging-monappc-monappc-frontend-tls
  dnsNames:
    - staging.monappc.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
