apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-monappc-monappc-frontend-cert
  namespace: prod-monappc-monappc-frontend
spec:
  secretName: prod-monappc-monappc-frontend-tls
  dnsNames:
    - monappc.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
