apiVersion: v1
kind: Service
metadata:
  name: prod-monappc-monappc-frontend-service
  namespace: prod-monappc-monappc-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: prod-monappc-monappc-frontend
